import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="min-h-screen bg-white dark:bg-zinc-900 pt-24 pb-16">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <h1 className="text-3xl font-bold text-zinc-900 dark:text-white mb-2">
            Terms of Service
          </h1>
          <p className="text-zinc-500 mb-8">Last updated: January 1, 2024</p>
          {[
            {
              title: "Acceptance of Terms",
              body: "By accessing and using ForkAI, you accept and agree to be bound by the terms and provision of this agreement.",
            },
            {
              title: "Use of Service",
              body: "ForkAI grants you a personal, non-exclusive, non-transferable license to use the platform for personal, non-commercial purposes.",
            },
            {
              title: "User Accounts",
              body: "You are responsible for safeguarding your account credentials and for all activities that occur under your account.",
            },
            {
              title: "AI Generated Content",
              body: "Content generated by our AI features is provided for informational purposes only. Always use your judgment when following AI-generated recipes.",
            },
            {
              title: "Limitation of Liability",
              body: "ForkAI shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the service.",
            },
            {
              title: "Contact Us",
              body: "If you have any questions about these Terms, please contact us at legal@forkai.com.",
            },
          ].map((section) => (
            <div key={section.title} className="mb-8">
              <h2 className="text-xl font-bold text-zinc-900 dark:text-white mb-3">
                {section.title}
              </h2>
              <p className="text-zinc-600 dark:text-zinc-300 leading-relaxed">
                {section.body}
              </p>
            </div>
          ))}
        </div>
      </main>
      <Footer />
    </>
  );
}
